name: build-all

on:
  push:
    paths-ignore:
    - '**/*.md'
    - 'examples/**'
  pull_request:
    paths-ignore:
    - '**/*.md'
    - 'examples/**'
    
jobs:
  example_matrix:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - if: ${{ runner.os == 'Linux' }}
      # if: matrix.os == 'ubuntu-latest'
        run: apt-get install libgtk2.0-dev
      - uses: actions/checkout@v2
      - name: Install Conan
        id: conan
        uses: turtlebrowser/get-conan@main

      - name: Conan version
        run: echo "${{ steps.conan.outputs.version }}"

      - name: Create default profile
        run: conan profile new default --detect

      # - name: Update profile
        # run: conan profile update settings.compiler.libcxx=libstdc++11 default        

      - name: Create build dir
        run: mkdir build

      - name: Conan build
        working-directory: build
        run: conan install .. --build=missing
